"""create emergency table

Revision ID: bb10badbfccb
Revises: 79f905fb2382
Create Date: 2026-08-19 11:49:47.583470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb10badbfccb'
down_revision: Union[str, Sequence[str], None] = '79f905fb2382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disasters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergencies_disaster_id'), 'emergencies', ['disaster_id'], unique=False)
    op.create_index(op.f('ix_emergencies_id'), 'emergencies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergencies_id'), table_name='emergencies')
    op.drop_index(op.f('ix_emergencies_disaster_id'), table_name='emergencies')
    op.drop_table('emergencies')
    # ### end Alembic commands ###
